"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export function ClientEditTokens({ clientId, hasGhlToken, hasMetaToken }: { clientId: string; hasGhlToken: boolean; hasMetaToken: boolean }) {
  const router = useRouter(); const [ghlPrivateToken, setGhl] = useState(""); const [metaAccessToken, setMeta] = useState(""); const [message, setMessage] = useState<string | null>(null);
  async function save() { const response = await fetch(`/api/clients/${clientId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...(ghlPrivateToken && { ghlPrivateToken }), ...(metaAccessToken && { metaAccessToken }) }) }); setMessage(response.ok ? "Credentials saved securely." : (await response.json()).error); if (response.ok) { router.push(`/clients/${clientId}`); router.refresh(); } }
  return <section className="rounded-lg border border-[#272722] bg-[#0c0c0b] p-5"><h2 className="text-sm font-medium">Replace integration credentials</h2><p className="mt-1 text-xs text-zinc-500">Leave a field empty to keep its current credential. Use this to replace the invalid GHL token.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs text-zinc-400">GHL private integration token ({hasGhlToken ? "configured" : "missing"})<input type="password" value={ghlPrivateToken} onChange={e => setGhl(e.target.value)} placeholder="Paste a new PIT token" className="mt-1.5 w-full rounded-md border bg-[#090909] px-3 py-2.5" /></label><label className="text-xs text-zinc-400">Meta access token ({hasMetaToken ? "configured" : "missing"})<input type="password" value={metaAccessToken} onChange={e => setMeta(e.target.value)} placeholder="Paste a new long-lived token" className="mt-1.5 w-full rounded-md border bg-[#090909] px-3 py-2.5" /></label></div>{message && <p className="mt-3 text-xs text-amber-300">{message}</p>}<button onClick={save} className="mt-5 rounded-md bg-[#d4af37] px-3 py-2 text-xs font-semibold text-black">Save credentials</button></section>;
}
